# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: potato-hacker-jekyll-template
author: "<your_name>"
email: "<your@mail>"
description: A simple Jekyll theme based on potatoes and hackers
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: "<github_username>"
facebook_username: "<facebook_username>"
twitter_username: "<twitter_username>"
# gplus_id: "<google_plus_id>"
linkedin_id: "<linkedin_id>"

# theme repository
theme_repository: "https://github.com/ArmlessJohn404/potato-hacker-jekyll-template"
theme_base: "light"        # Theme pallente (light | dark)
theme_switch: on         # Show color switch (on | off)

# extra settings
collections:
  projects:
    output: true
  about:
    output: true
  blog:
    output: true
columns: 8   # columns and offset must be integers and columns+2*offset must add to 12
offset: 2    # columns and offset must be integers and columns+2*offset must add to 12
avatar_image: "assets/img/avatar.jpg"
avatar_description: "My name is Popotato and I'm a HACKER."

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
